### ISSUE TITLE
when install on issabel

### ISSUE THREAD

**Issue by Ma7m0d** [garronej/chan-dongle-extended#2]
[root@PBX ~]# [root@PBX ~]# wget -nc -q -O - garronej.github.io/chan-dongle-extended-pages/install.sh | sudo bash
-bash: [root@PBX: command not found
[root@PBX ~]# wget -nc -q -O - garronej.github.io/chan-dongle-extended-pages/install.sh | sudo bash
Directory /usr/share/dongle already exsist, uninstalling previous install
wget: unrecognized option '--show-progress'
Usage: wget [OPTION]... [URL]...

Try `wget --help' for more options.
Extractingtar (child): /tmp/dongle.tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
rm: cannot remove ‘/tmp/dongle.tar.gz’: No such file or directory
bash: line 39: ./node: No such file or directory
[root@PBX ~]#

**Comment by garronej** [comment]
Hi,  
Seem's like the version of wget installed on your system is degradated compared to the one that comes with debian.  
What flavor of linyx are you runing this on?

**Comment by garronej** [comment]
This app only support  Debain, Ubuntu and Raspbian

**Comment by Ma7m0d** [comment]
Is there no solution to run on Centosto run issabel, and it has every job instead of working on a specific server?

**Comment by Ma7m0d** [comment]
i need php file to run cmd dongle show devices on centos and get output in same page can yo help me ? to be able to follow the dongle via the control panel, np need cli commands

**Comment by garronej** [comment]
Hi,  
I am sorry but chan-dongle-extended is only compatible with Debian based system and Issabel only release an ISO for CentOS.  
I guess it should be possible to get chan-dongle-extended to install on CentOS but it's not straight forward.

**Comment by Ma7m0d** [comment]
> Hi,
> I am sorry but chan-dongle-extended is only compatible with Debian based system and Issabel only release an ISO for CentOS.
> I guess it should be possible to get chan-dongle-extended to install on CentOS but it's not straight forward.

ok thnx but what about help on
i need php file to run cmd dongle show devices on centos and get output in same page can yo help me ? to be able to follow the dongle via the control panel, np need cli commands

**Comment by garronej** [comment]
The bash command should be: `asterisk -rx 'dongle show devices'`

And to execute it from a PHP script: https://www.php.net/manual/en/function.shell-exec.php

**Comment by Ma7m0d** [comment]
> The bash command should be: `asterisk -rx 'dongle show devices'`
> 
> And to execute it from a PHP script: https://www.php.net/manual/en/function.shell-exec.php

ok thanx i well tray
