### ISSUE TITLE
Update repositories

### ISSUE THREAD

**Issue by kauczu** [garronej/chan-dongle-extended#3]
Hi,
i think you should update wodekes asterisk-chan-dongle repository in file
https://github.com/garronej/chan-dongle-extended/blob/master/dist/bin/installer.js (line 928) because it pull outdated version of chan-dongle.
Commit you pointed to on installer.js file doesn't show recipient name properly in received SMS. It show raw PDU. It must be decoded (7 bit).
Latest wodekes asterisk-chan-dongle repository is free from this bug.

Greetings.
Kauczu

**Comment by garronej** [comment]
Hi @kauczu,
I think you'll be pleased to now that `chan-dongle-extended` has it's own way of handling SMS that is far superior than wodekes's will ever be.  
- Multipart SMS:
Reliably Send and receive multipart SMS, fix all encoding problems.
- SMS status report:
Confirm that SMS have been successfully delivered.

The OG chan-dongle is only used for phone calls.  

There is three different API for managing SMSs with chan-dongle-extended:  
1) A [node.js client](https://github.com/garronej/chan-dongle-extended-client) (If you need help to set it up, I can guide you)
2) A cli tool (`dongle send --help` and `dongle messages --help` for more info)
2) Via the dialplan [documentation](https://github.com/garronej/chan-dongle-extended-pages/blob/master/index.md#handling-multi-parts-sms-via-the-dialplan)

[Documentation website](https://garronej.github.io/chan-dongle-extended-pages/)

Cheers.

**Comment by garronej** [comment]
Is there some news on wodekes's fork on the voice call side that would make worth it to [update the pinned commit](https://github.com/garronej/chan-dongle-extended/blob/2be42c6a9aada83d3c4fabf4680376dfc2fccbce/src/bin/installer.ts%23L946) ?

**Comment by kauczu** [comment]
> `chan-dongle-extended` has it's own way of handling SMS 

Thanks for clearing it for me. 

Can you please be kind and share it how to properly display GSM-7 encoded sender name (if it's not a regular number)  in receieved SMS using `chan-dongle-extended`?

![image](https://user-images.githubusercontent.com/63737120/133002227-42fbebb2-c465-429f-8f67-ccdee10d09b1.png)
On screenshot: received messages have sender name in "number" field encoded in GSM-7, and it should be converted.

As I studied  your project documentation I didn't find how to set this up properly.

Is `chan-dongle-extended-client` will handle it properly?
Maybe is worth to try to install `chan-dongle-extended-client`

> Is there some news on wodekes's fork on the voice call side that would make worth it to update the pinned commit ?

I think it's not necessary at the moment.

**Comment by garronej** [comment]
Damn there is a bug.  
We can colaborate on fixing it if you'd like.  
Under the hood what `chan-dongle-extended` is using is [node-pyton-messaging](https://github.com/garronej/node-python-messaging) I encourage you to read at least the beginning for the readme it will enlighten you.  

 What you'll need is to get the PDU of an SMS that isn't correctly decoded. Copy it and start [hacking around](https://github.com/garronej/node-python-messaging#usage) until you get the number decoded as expected.  

Feel free to correct the bug at [the JavaScript level](https://github.com/garronej/node-python-messaging/blob/3447b45a59ea0aecb33bb425f3db76a043a6b1f7/src/lib/bridge.ts#L271-L289) or [directly at the source in python](https://github.com/garronej/python-messaging)  

I grant you full access to [node-python-messaging](https://github.com/garronej/node-python-messaging) and [garronej/python-messaging](https://github.com/garronej/python-messaging) so you can commit directly to theses repos.  
`node-python-messaging` is always using [the latest commit](https://github.com/garronej/node-python-messaging/blob/master/requirements.txt) of `garronej/python-messaging`.   

If you manage to fix the bug, I will release a new version of `chan-dongle-extended` incorporating your changes.  

> Is chan-dongle-extended-client will handle it properly?
> Maybe is worth to try to install chan-dongle-extended-client

No, `chan-dongle-extend-client` won't fix any bug. It's juste a client that let you send/receive SMS and manage phone calls using node.js instead of writing Asterisk dialplan.

**Comment by kauczu** [comment]
> We can colaborate on fixing it if you'd like.
> Under the hood what `chan-dongle-extended` is using is [node-pyton-messaging](https://github.com/garronej/node-python-messaging) I encourage you to read at least the beginning of the readme it will enlighten you.

I don't know if I can make it but I will try.

**Comment by garronej** [comment]
Are you able to get the PDU of the original message?

**Comment by kauczu** [comment]
I can give you - now - PDU of three older messages from time when I was using an ancient version of asterisk-chan-dongle (version that could not parse incoming message with alphanumeric TP-OA field and luckily wrote to log a complete PDU):

`07918497908952F72414D0D2F29C1EAEB7C3F4F4180000022181714315405A557D5E0D5AD6E16F771D0495BFDBEF715EED2E9FDF3A100D292743D72C50589C07CDD76FB93E3FA787C7203D481E1687E97510F90D82A7CBF2FB5C5F3EBF41FA70FB7D4F97DDE930E8ED66A7DDE510`

`07918497908952F72414D0D2F29C1EAEB7C3F4F4180000022181714400405A557D5E0D5AD6E16F771D0495BFDBEF715EED2E9FDF3A908D6EA6CB8A2C50589C07CDD76FB93E3FA787C7203D481E1687E97510F90D82A7CBF2FB5C5F3EBF41FA70FB7D4F97DDE930E8ED66A7DDE510`

`07918497908952F72414D0C374F80D4AD2C3EC74180000022181710584406B50B93EAF2EB3D3F3761EA40FB7DFF774D99D2E8740C4F79C1E968FF5F9761EA42E83C86FD0305D16A7CBA0F7DA058AE174B49C0B346D87C77A77F9FC06E952A01668980EBF41497A989D0E838E6FB9FE7D075DD365F6FA0D7FB3E7EB3408`

**Comment by garronej** [comment]
Hum stranges,
It seems like `node-python-messaging` is doing it's job perfectly. 

![image](https://user-images.githubusercontent.com/6702424/133150113-a69245d7-ee52-483b-8a6c-df126b418bd7.png)

**Comment by garronej** [comment]
This is the code I used:  

```typescript

process.once("unhandledRejection", error => { throw error; });

import {
	decodePdu,
} from "../lib/index";

const pdus = [
	"07918497908952F72414D0D2F29C1EAEB7C3F4F4180000022181714315405A557D5E0D5AD6E16F771D0495BFDBEF715EED2E9FDF3A100D292743D72C50589C07CDD76FB93E3FA787C7203D481E1687E97510F90D82A7CBF2FB5C5F3EBF41FA70FB7D4F97DDE930E8ED66A7DDE510",
	"07918497908952F72414D0D2F29C1EAEB7C3F4F4180000022181714400405A557D5E0D5AD6E16F771D0495BFDBEF715EED2E9FDF3A908D6EA6CB8A2C50589C07CDD76FB93E3FA787C7203D481E1687E97510F90D82A7CBF2FB5C5F3EBF41FA70FB7D4F97DDE930E8ED66A7DDE510",
	"07918497908952F72414D0C374F80D4AD2C3EC74180000022181710584406B50B93EAF2EB3D3F3761EA40FB7DFF774D99D2E8740C4F79C1E968FF5F9761EA42E83C86FD0305D16A7CBA0F7DA058AE174B49C0B346D87C77A77F9FC06E952A01668980EBF41497A989D0E838E6FB9FE7D075DD365F6FA0D7FB3E7EB3408"
];

(async () => {

	for (const pdu of pdus) {

		const sms = await decodePdu(pdu);

		console.log(sms);


	}


})();

```

**Comment by garronej** [comment]
I made `node-ptrhon-messaging` easyer to install:  
```bash
git clone https://github.com/garronej/node-python-messaging
cd node-python-messaging
npm install
npm run tsc
node dist/test/test_issue3.js
```

This will run the code to generate the output. 

You'll need tu update [this file](https://github.com/garronej/node-python-messaging/blob/master/src/test/test_issue3.ts) if you want to try with another PDU.  
If you edit the file you should run `npm run tsc` again or `npx tsc -w` for compiling in watch mode then run `node dist/test/test_issue3.js` again.  

To help you I would need at least one PDU that do note decode properly.

**Comment by kauczu** [comment]
Thanks. I'll test it tomorrow and let you know.

**Comment by kauczu** [comment]
It' parsing PDU well.

I used two PDU that I receieved now:

`07918497908952F76010D0C274992C7FBBD7610008129051713183808C0500037A02010057006900740061006A002C002000540079006D0063007A00610073006F0077006500200068006100730142006F0020006C006F0067006F00770061006E0069006100200064006F00200070006F007200740061006C00750020006D006F006A0061002E00620069006500640072006F006E006B0061002E0070006C00200074006F003A0020`

`07918497908952F76410D0C274992C7FBBD7610008129051713183800E0500037A02020032003500370035`
![image](https://user-images.githubusercontent.com/63737120/133461947-379e11d1-0a3f-4f00-b010-a39c98ec32e8.png)

**Comment by garronej** [comment]
But when you run `dongle messages` the number doesn't show well??!

**Comment by kauczu** [comment]
> But when you run `dongle messages` the number doesn't show well??!

Exactly.

**Comment by garronej** [comment]
I don't understand how this is possible. I forget to compile the latest build for your architecture.  
Can you run `uname -m` on the device running `chan-dongle-extended` and paste the response here.

**Comment by kauczu** [comment]
`uname -m`
i686

I don't know. Maybe it's up to python version? I have installed two versions: 2.7.18 and 3.9.2

**Comment by garronej** [comment]
> I don't know. Maybe it's up to python version? I have installed two versions: 2.7.18 and 3.9.2

Unlikely, it would crash. 

> i686 

Ok let me check

**Comment by garronej** [comment]
Ok I am pretty sure I know what the bug is.  

You are running a very outdated version of `chan-dongle-extended` because I didn't bother building for 32bits in a very long while.  

Problem is that I don't have access to a x86 to build the new version for you.  
I can tell you how to do it or, if you give me SSH access to your machine I can do it for you.

**Comment by kauczu** [comment]
> I can tell you how to do it 
Yes, please. 

I have an old HP terminal wich uses 32bit Intel Atom. I wanted to utilise this device. That is why i'm using ancient 32bit arch. Maybe it is time to move to 64 bits...

**Comment by garronej** [comment]
No, no, it's perfect to use your old laptop for that purpose. 

> Yes, please.

Ok then, first you need to go to your mail. I sent you an invitation giving you access to this repo: https://github.com/garronej/releases  
Then you need to generate a PERSONNAL ACCESS TOKEN:  

![image](https://user-images.githubusercontent.com/6702424/133490200-996a9713-0f82-4f45-b4a9-dba122f573f6.png)
![image](https://user-images.githubusercontent.com/6702424/133490270-77eb0ac3-fb37-42a2-ba7b-a3483b9b5f93.png)
![image](https://user-images.githubusercontent.com/6702424/133490298-2a127ab3-59d1-4614-b98d-2a8e5bf524b6.png)
![image](https://user-images.githubusercontent.com/6702424/133490329-60a7269d-ee47-425b-b415-b9b57253cdec.png)
![image](https://user-images.githubusercontent.com/6702424/133490577-258f56f2-fadc-43f6-b0a7-ea1e8bba3ac7.png)

Then copy your token and  run this (on the host that runs `chan-dongle-extended`)

```bash
# make sure that python --version shows 2.x  

# You'll need node v8
curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
sudo apt-get install -y nodejs
sudo npm install -g npm

git clone https://github.com/garronej/chan-dongle-extended
cd chan-dongle-extended
echo YOUR_PERSONAL_ACCESS_TOKEN > res/PUTASSET_TOKEN
npm run partial_install
npm run release
```

**Comment by kauczu** [comment]
I fell into my own trap.
I installed Debian Bullseye (11). Unfortunately Node.js 8.x support (that I suppose to install) ends on Debian Buster (10).
So now I am going to install Debian Buster, and then will try to build chan-dongle-extended as you mentioned above.

I'll keep you posted.

**Comment by garronej** [comment]
I don't think you necessary need to downgrade.  
The version of `chan-dongle-extended` you are running is using node v8.  
If I where you I try installing node using [this method](https://github.com/nodejs/help/wiki/Installation#how-to-install-nodejs-via-binary-archive-on-linux).  
In your case:
```bash
VERSION=v0.8.9
DISTRO=linux-x86
```

**Comment by kauczu** [comment]
> You are running a very outdated version of chan-dongle-extended because I didn't bother building for 32bits in a very long while.

I decided to leave 32bit arch.
I will try `chan-dongle-extended` on 64bit soon.

**Comment by garronej** [comment]
Unfortunately you will have to compile the newer version on 64bit as well. The only arch for which I have compiled the latest build is ARM (arch used by boards like the raspberry pi)

**Comment by garronej** [comment]
I'll try compile it in the cloud

**Comment by garronej** [comment]
@kauczu I compiled the latest version for 64bit. It should work fine now. Let me know if you have any problem.
