### ISSUE TITLE
User issue once installed

### ISSUE THREAD

**Issue by jahaddow** [garronej/chan-dongle-extended#7]
My install completes successfully on Debian 11 with Asterisk 16 & Freepbx 16. 

But once opening freepbx it says it can't connect to asterisk and my log also fills with "manager.c: 127.0.0.1 tried to authenticate with nonexistent user 'admin'" & "manager.c: 127.0.0.1 failed to authenticate as 'admin'"

The dongle is connected and working however. As soon as I run the uninstall script Freepbx/asterisk works fine again.

**Comment by rdmitry0911** [comment]
> My install completes successfully on Debian 11 with Asterisk 16 & Freepbx 16.
> 
> But once opening freepbx it says it can't connect to asterisk and my log also fills with "manager.c: 127.0.0.1 tried to authenticate with nonexistent user 'admin'" & "manager.c: 127.0.0.1 failed to authenticate as 'admin'"
> 
> The dongle is connected and working however. As soon as I run the uninstall script Freepbx/asterisk works fine again.

Installation script creates a new manager.conf in /etc/asterisk while preserving the old one in /usr/share/dongle/working_directory Just put back original [admin] section to /etc/asterisk/manager.conf and restart service with fwconsole restart

**Comment by jahaddow** [comment]
Thanks a lot, fixed my issue.
