### ISSUE TITLE
k3765 dongle working call in, out, but no sound

### ISSUE THREAD

**Issue by vegtelenmt2** [garronej/chan-dongle-extended#8]
Hello!

My install you script. 
My server: debian 11 64 bit
5.10.0-21-amd64 #1 SMP Debian 5.10.162-1 (2023-01-21) x86_64

My dongle: K3765

The call starts, I can pick up with the other person, I can make outgoing and incoming calls. But when I pick it up, there is no sound on either side, no matter how much I talk into either side.

With the dongle, if I put the call on hold with the virtual one, the call hold tone doesn't sound either. However, the system says that it has been started. It's all completely deaf. No idea what the problem could be?

Thanks!

**Comment by garronej** [comment]
Hi @vegtelenmt2,  
Have you had a look at this graphic:  
![](https://cloud.githubusercontent.com/assets/6702424/26686554/9253bc18-46ed-11e7-9bce-cad8e2396435.png)

**Comment by garronej** [comment]
Well never mind, it's about gain control and buffering.  If you can't here anything it probably isn't it...  
Try ChatGPT maybe...

**Comment by vegtelenmt2** [comment]
Sorry, my topic can be closed because it is already working. I rewrote the following and commented them out: ;audio=/dev/ttyUSB1
;data=/dev/ttyUSB0

Then I added the following lines in dongle.conf:

imei=
imsi=

I filled them in correctly and it works perfectly.
But I've been struggling with this for months, that the sound didn't work at all. That was the problem.

**Comment by garronej** [comment]
Great, I'm happy for you and thank you for taking the time ti give feedback
